- ansible.builtin.import_tasks: fedora.yml
  when: (vm_os == 'fedora')

- ansible.builtin.import_tasks: debian.yml
  when: (vm_os == 'debian' )

- ansible.builtin.import_tasks: windows.yml
  when: (vm_os == 'windows')